###########################################################################
#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# To change its version, see the available Tags on the Docker Hub:
#    https://hub.docker.com/r/fromscratch/ruby/tags/
#
# Note: Base Image name format fromscratch/ruby:{ruby-version}-sbt-{sbt-version}
#
###########################################################################

FROM fromscratch/ruby:2.3.1-node-11.15.0

LABEL maintainer "from scratch Co.Ltd."

###########################################################################
# variables:
###########################################################################

ENV SBT_VERSION 0.13.12

###########################################################################
# sbt binary download
###########################################################################

RUN \
  curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  sbt sbtVersion

CMD ["/bin/sh"]
