###########################################################################
#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
# To change its version, see the available Tags on the Docker Hub:
#    https://hub.docker.com/r/fromscratch/ruby/tags/
#
# Note: Base Image name format fromscratch/ruby:{ruby-version}-amazonlinux{amazonlinux-version}-{ami-version}
#
###########################################################################

FROM amazonlinux:2.0.20181114

LABEL maintainer "from scratch Co.Ltd."

###########################################################################
# Versions:
###########################################################################

ENV RUBY_MAJOR 2.6
ENV RUBY_VERSION 2.6.2
ENV NODE_VERSION 10.18.1
ENV YARN_VERSION 1.21.1

###########################################################################
# Set Timezone
###########################################################################

ENV TZ Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

###########################################################################
# Common:
###########################################################################

RUN yum update -y && \
    yum install -y git gcc gcc-c++ openssl openssl-devel readline readline-devel \
    mysql mysql-devel bzip2 postgresql postgresql-devel sudo tar libXi libX11 \
    libXcomposite libXcursor libXdamage libXext libXtst libXi.so.6 cups-libs \
    libXScrnSaver libdrm libXrandr libgbm alsa-lib atk at-spi2-atk pango gtk3

###########################################################################
# Ruby:
###########################################################################

RUN mkdir -p /build/ruby && \
    curl -s https://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.gz | tar -C /build/ruby -xzf - && \
    cd /build/ruby/ruby-$RUBY_VERSION && \
    ./configure --disable-install-doc && \
    make && make install && \
    gem install bundler && \
    rm -fr /build/ruby

###########################################################################
# add user 'circleci':
# cf. circleci/ruby:2.6.2-node
# https://hub.docker.com/r/circleci/ruby/tags/
###########################################################################

RUN groupadd --gid 3434 circleci \
  && useradd --uid 3434 --gid circleci --shell /bin/bash --create-home circleci \
  && echo 'circleci ALL=NOPASSWD: ALL' >> /etc/sudoers.d/50-circleci \
  && echo 'Defaults    env_keep += "DEBIAN_FRONTEND"' >> /etc/sudoers.d/env_keep

###########################################################################
# node:
###########################################################################

ENV HOME /home/circleci
ENV NVM_DIR /home/circleci/.nvm

RUN echo $HOME && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.33.8/install.sh | bash && \
    . $NVM_DIR/nvm.sh && \
    nvm install ${NODE_VERSION} && \
    nvm use ${NODE_VERSION} && \
    nvm alias ${NODE_VERSION} && \
    npm install eslint --save-dev && \
    echo "" >> /home/circleci/.bashrc && \
    echo 'export NVM_DIR="/home/circleci/.nvm"' >> /home/circleci/.bashrc && \
    echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> /home/circleci/.bashrc && \
    chmod -R 755 $NVM_DIR && \
    chown -R circleci:circleci $NVM_DIR

###########################################################################
# YARN:
###########################################################################

RUN [ -s "$NVM_DIR/nvm.sh" ] && \
    . $NVM_DIR/nvm.sh && \
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION} && \
    echo "" >> /home/circleci/.bashrc && \
    echo 'export PATH="/home/circleci/.yarn/bin:$PATH"' >> /home/circleci/.bashrc && \
    chmod -R 755 /home/circleci/.yarn && \
    chown -R circleci:circleci /home/circleci/.yarn && \
    chmod -R 755 /home/circleci/.config && \
    chown -R circleci:circleci /home/circleci/.config

###########################################################################
# awscli and socat:
###########################################################################

RUN curl -o- https://bootstrap.pypa.io/get-pip.py | python && \
    pip install pip --upgrade && \
    pip install awscli

RUN mkdir -p /home/circleci/target && \
    chmod -R 755 /home/circleci/target && \
    chown -R circleci:circleci /home/circleci/target

WORKDIR /home/circleci/target

USER circleci

CMD ["/bin/bash"]
